CREATE TABLE `movements` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`title` text NOT NULL,
	`reason` text,
	`amount` integer NOT NULL,
	`currency_code` text NOT NULL,
	`payment_mode` text,
	`installment_count` integer,
	`interest_free` integer DEFAULT false NOT NULL,
	`occurred_at` text NOT NULL,
	`source_card_id` text,
	`destination_card_id` text,
	`expense_id` text,
	`category_id` text,
	`active` integer DEFAULT true NOT NULL,
	`registered_at` text NOT NULL,
	`updated_at` text,
	`deleted_at` text,
	FOREIGN KEY (`source_card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`destination_card_id`) REFERENCES `cards`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`expense_id`) REFERENCES `expenses`(`id`) ON UPDATE no action ON DELETE restrict,
	FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON UPDATE no action ON DELETE restrict
);
